#version of docker compose syntax
version: "3.9"

#spedicy servies. 1 or more needed for your app
services:
  #name of service
  app:
    #build the docker file inside our current directory
    build: 
      context: .
      args:
        - DEV=true
    #maps 8000 our machine to our container 8000
    ports:
      - "8000:8000"
    #mapings the app directory to the app directory in our container
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    #command that is used to run the server
    #the defalt comamnd to use if we dont specify a command
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db #host name we will connect to, the service name
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=admin123
    depends_on:
      - db

  db:
    #alpine is light wright
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    #set configuration for the new db service
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=admin123




volumes:
  dev-db-data:
  dev-static-data:
      